Tativega/Ecommerce-chiqualaiz

front/src/containers/NavbarContainer.jsx

navBar state opcional

---

back/public/style.css
front/src/components/Greeting.jsx
front/src/components/NavBar.jsx
front/src/components/SearchBar.jsx
front/src/css-modules/navBar.module.css

-styling background
-styling navbar

Nav bar style

---

front/src/components/Main.jsx
front/src/components/SearchBar.jsx
front/src/containers/RegisterContainer.jsx
front/src/containers/SingleBookContainer.jsx

Bugs arreglados. Página funciona.

pagina funcionando

---

back/routes/index.js
back/routes/users.js
front/src/components/Greeting.jsx
front/src/components/Login.jsx
front/src/components/NavBar.jsx
front/src/components/SingleBook.jsx
front/src/containers/LoginContainer.jsx
front/src/containers/NavbarContainer.jsx
front/src/css-modules/greeting.module.css
front/src/store/actions/users.js

Login 100% funcional y tarjeta

Login funcional

---

front/src/components/Books.jsx

Fixed minor bug in singleBookPage

---

front/src/components/SingleBook.jsx
front/src/containers/SingleBookContainer.jsx

Modificacion desde el front para que muestre sólo los primeros 50 caracteres de la descripción.

descripcion de 50 caracteres max

---

back/seed.js
front/src/components/Books.jsx
front/src/components/SingleBook.jsx
front/src/containers/SingleBookContainer.jsx

Corrección del seeder, tiraba error al intentar agregar libros sin autor (aún lo hace, sólo no dejé ninguno sin completar ese campo). Agregado de más libros para probar el paginado.

correccion del seed y agregado de libros

---

front/src/components/Books.jsx
front/src/css-modules/Books.module.css

El puntero cambia a una mano al realizar hover sobre los botones de cambio de página. Se agrega una clase .active para la página actual.

pagination hover icon and active status

---

back/routes/index.js
front/src/components/Register.jsx
front/src/containers/RegisterContainer.jsx
front/src/store/actions/users.js

- registration browser validation completed

Registration browser validation

---

front/src/components/Login.jsx

Login style

---

back/routes/index.js
back/routes/sessions.js
back/routes/users.js
front/src/store/actions/users.js

architecture fixed to be more restful (Changed login/register for post users, post sessions

fix architecture to be more restful

---

back/npm-debug.log
back/resolvers/books.js
back/routes/books.js
front/src/components/Books.jsx
front/src/components/Dashboard.jsx
front/src/components/Main.jsx
front/src/components/addBook.jsx
front/src/containers/AddBookContainer.jsx
front/src/containers/BooksContainer.jsx
front/src/containers/DashboardContainer.jsx
front/src/containers/SingleBookContainer.jsx
front/src/store/actions/books.js

admin puede acceder a cread books desde su dashboard
al formulario funcion: Se crea un libro
El formulario da feedback tanto en caso de éxito o de fracaso.

admin-crea-books

---

front/src/components/Books.jsx
front/src/components/NavBar.jsx
front/src/containers/SearchBarContainer.jsx

Se puede filtrar, cambiar de página y pasar el link de esa url para r directamente a esa búsqueda y página específicas.
(hay un pequeño bug asociado al botón Next que recuerda el máximo de libros totales, y no los filtrados)

Se puede filtrar, cambiar de página y pasar el link de esa url

---

front/src/components/Books.jsx

Basicamente agregando un estado local en Books para trackear el máximo de páginas y modificandolo en componentDidUpdate

solucionado el bug al filtrar y presionar next

---

back/seed.js
front/src/components/NavBar.jsx
front/src/components/SearchBar.jsx
front/src/containers/NavbarContainer.jsx
front/src/containers/SearchBarContainer.jsx

La barra de busqueda actualiza por caracter agregado y lleva directamente al resultado cuando sólo hay 1 y se presiona enter.
(solo falta verificar por caracteres solo alfanuméricos)

La barra de busqueda actualiza por caracter agregado

---

back/npm-debug.log
back/resolvers/books.js
back/routes/books.js
front/src/components/Dashboard.jsx
front/src/components/Main.jsx
front/src/components/NavBar.jsx
front/src/components/SingleBook.jsx
front/src/components/addBook.jsx
front/src/containers/AddBookContainer.jsx
front/src/containers/DashboardContainer.jsx
front/src/containers/SingleBookContainer.jsx
front/src/store/actions/books.js

admin puede editar

---

back/npm-debug.log
back/resolvers/books.js
back/routes/books.js
front/src/components/SingleBook.jsx
front/src/containers/SingleBookContainer.jsx
front/src/store/actions/books.js

administrador puede borrar productos accediendo al single page y clickeando en eliminar

admin puede borrar productos

---

back/resolvers/books.js
back/routes/books.js
front/src/components/Genres.jsx
front/src/components/NavBar.jsx
front/src/components/SearchBar.jsx
front/src/containers/GenreContainer.jsx
front/src/containers/NavbarContainer.jsx
front/src/store/actions/books.js
front/src/store/constants/index.js
front/src/store/reducers/books-reducer.js
front/src/store/reducers/index.js

filtro de categoria, sin funcionalidad

filtro de categoria, sin funcionalidad

---

front/src/containers/NavbarContainer.jsx

corrijo typo en NavBarContainer

corrijo typo en NavBarContainer

---

back/npm-debug.log
back/public/style.css
front/package.json
front/src/components/Books.jsx
front/src/components/Dashboard.jsx
front/src/components/Greeting.jsx
front/src/components/Kart.jsx
front/src/components/Login.jsx
front/src/components/Main.jsx
front/src/components/NavBar.jsx
front/src/components/Register.jsx
front/src/containers/BooksContainer.jsx
front/src/containers/KartContainer.jsx
front/src/css-modules/Books.module.css
front/src/css-modules/kart.module.css
front/src/css-modules/register.module.css
front/src/store/actions/cart.js
front/src/store/constants/index.js
front/src/store/reducers/cart-reducer.js
front/src/store/reducers/index.js
front/webpack.config.js

- Arreglado conflicto CSS MODULES (Presten atención a como cambio el estilo)
- Carrito no log de state global añade objetos.

css modules fixed y non logued user carrito añadir libros

---

back/config/passport.js
front/src/components/Books.jsx
front/src/components/Genres.jsx
front/src/components/Kart.jsx
front/src/containers/KartContainer.jsx
front/src/containers/LoginContainer.jsx
front/src/store/actions/books.js
front/src/store/actions/cart.js
front/src/store/constants/index.js
front/src/store/reducers/books-reducer.js

Usuario deslogueado tiene carrito persistente

Usuario deslogueado persiste

---

back/resolvers/carts.js
back/routes/carts.js
front/src/components/Kart.jsx
front/src/containers/KartContainer.jsx
front/src/store/actions/cart.js
front/src/store/actions/users.js

Carrito deslogueado se agrega y se suma con el usuario logueado

---

back/resolvers/carts.js
front/src/components/Login.jsx
front/src/containers/LoginContainer.jsx
front/src/css-modules/greeting.module.css

Se modifico el modal de Login para que desaparezca cuando se clickea en Register.

cambios-modal-login

---

front/src/components/Historial.jsx
front/src/components/Kart.jsx

bug stock y bug botones

---

back/public/style.css
back/resolvers/books.js
front/src/components/AddGenre.jsx
front/src/components/Checkout.jsx
front/src/components/EditGenre.jsx
front/src/components/Genres.jsx
front/src/containers/AddGenreContainer.jsx
front/src/containers/EditGenreContainer.jsx
front/src/store/actions/books.js

- Check de categorias es excluyente y si elegís al mismo, se deselije y vuelve a tirar una lista total
- Crear género ahora cierra la pantalla en caso de éxito, y da feedback negativo en caso de fracaso.
- Problemas visuales de editar genero

Bugs de géneros arreglados

---

back/routes/pedidos.js
back/routes/users.js
front/src/components/AdminOrders.jsx
front/src/containers/AdminOrdersContainer.jsx

Se agregaron ruta que faltaba para componente de ordenes desde le perfil de administrados

total-ordenes-admin

---

back/models/Book.js
front/src/components/Reviews.jsx
front/src/components/Sort.jsx
front/src/store/actions/books.js
front/src/store/reducers/books-reducer.js

Ordena libros por titulo, precio o rating

Ordenar libros

---

front/src/css-modules/historial.module.css
front/src/css-modules/kart.module.css

los botones del carrito ya no cubren la navbar y tienen shadows

mejora estilo del carrito

---

back/models/index.js
back/routes/pedidos.js
back/routes/users.js
front/src/components/AdminOrders.jsx
front/src/containers/AdminOrdersContainer.jsx
front/src/containers/CheckoutContainer.jsx
front/src/store/actions/users.js
front/src/store/constants/index.js
front/src/store/reducers/user-reducer.js

El componente de historial de pedidos ahora puede editar el status de las ordenes.

admin-status

---

back/models/User.js
back/routes/users.js
front/src/components/EditProfile.jsx
front/src/components/Greeting.jsx
front/src/components/Main.jsx
front/src/containers/EditProfileContainer.jsx
front/src/css-modules/greeting.module.css
front/src/store/actions/users.js

- Se agrego componente EditProfile y container EditProfileContainer
- En el componente se puede realizar una actualizacion de datos y de la contraseña.
- Se agrego en el modelo User un "beforeUpdate" para actualizar la contraseña y datos del usuario.
- Se agrego span:hover al nombre del usuario en el Greeting para que se redirija al componente EditProfile

edit profile terminado

---

back/routes/pedidos.js
front/src/store/actions/users.js

Se corrigieron rutas en Action-users y back-pedidos

rutas-corregidas-admin

---

back/models/Review.js
front/src/components/OrderPlaced.jsx
front/src/components/Reviews.jsx
front/src/components/SingleBook.jsx
front/src/containers/CheckoutContainer.jsx
front/src/containers/SingleBookContainer.jsx

agrego rating como campo obligatorio para poder dejar review

Tati branch que anda
